name: Publish to Github Pages

on:
  push:

jobs:
  publish-pages:
    name: Publish Pages
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.18'
      - uses: bahmutov/npm-install@v1
      - name: Build
        run: yarn build
      - name: Publish Pages
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages
          folder: docs
          
      